version: '3.7'

services:
    web:
        container_name: opencarbonmap_web        
        build: ./app
        command: gunicorn carbonmap.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/static
        expose:
            - 8000
        env_file:
            - ./app/.env.prod
        environment:
            - SQL_HOST=db    
        depends_on:
            - db

    db:
        container_name: opencarbonmap_db       
        image: postgis/postgis
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./app/.env.prod

    nginx:
        container_name: opencarbonmap_nginx        
        build: ./nginx
        volumes:
            - static_volume:/home/app/web/static            
        ports:
            - 80:80
        depends_on:
            - web            

volumes:
    postgres_data:
    static_volume:
    
    
