version: '3.7'

services:
    web:
        container_name: opencarbonmap_web        
        build: ./app
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        env_file:
            - ./app/.env.dev
        environment:
            - SQL_HOST=db
        depends_on:
            - db
        volumes:
            - ./app/:/usr/src/app/
    
    db:
        container_name: opencarbonmap_db        
        image: postgis/postgis
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./app/.env.dev
            
volumes:
    postgres_data:

